### ISSUE TITLE
Problem reading .GRIB

### ISSUE THREAD

**Issue by 1andrew69** [1andrew69/Andres#1]
Hello, I having problems reading a Grib file. When i try read the file appears :

Error using ncdataset (line 91)
Failed to open fcst_surf.1958010100

Error in cfdataset (line 55)
            obj = obj@ncdataset(url);

Error in ncgeodataset (line 20)
            obj = obj@cfdataset(url);

Caused by:
    Error using ncdataset (line 75)
    Java exception occurred:
    java.lang.RuntimeException: java.lang.NoSuchFieldError: paramTable

    	at ucar.nc2.NetcdfFile.<init>(NetcdfFile.java:1535)

    	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:887)

    	at ucar.nc2.NetcdfFile.open(NetcdfFile.java:496)

    	at ucar.nc2.dataset.NetcdfDataset.openOrAcquireFile(NetcdfDataset.java:693)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:424)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:407)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:392)

    	at ucar.nc2.dataset.NetcdfDataset.openDataset(NetcdfDataset.java:379)

    Caused by: java.lang.NoSuchFieldError: paramTable

    	at ucar.nc2.grib.grib1.Grib1Iosp.open(Grib1Iosp.java:129)

    	at ucar.nc2.NetcdfFile.<init>(NetcdfFile.java:1499)

    	... 7 more

Could someone help me_

Thanks!

**Comment by 1andrew69** [comment]
I use matlab 2017b whit a java version 'Java 1.8.0_121-b13 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode'. I uninstalled all the toolboxes except the 'Mapping Toolbox' but it doesn't work.
